<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SachSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('saches')->delete();
        DB::table('saches')->truncate();
        DB::table('saches')->insert([
            //1 Kinh Dị
            [
                'ten_sach'     => 'Dracula',
                'slug_sach'    => Str::slug('Dracula'),
                'id_the_loai'  => '1',
                'id_chuyen_muc'=> '1',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://i.thenile.io/r1000/9781435159570.jpg?r=603c14c193672',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Frankenstein',
                'slug_sach'    => Str::slug('Frankenstein'),
                'id_the_loai'  => '1',
                'id_chuyen_muc'=> '1',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.Z9MolIsbuG_uCRLWpfQotwHaLD?w=202&h=302&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'The Exorcist ',
                'slug_sach'    => Str::slug('The Exorcist'),
                'id_the_loai'  => '1',
                'id_chuyen_muc'=> '1',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.-JROLrol9XfKdAUEbAGmYwHaLX?w=201&h=309&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'The Shining ',
                'slug_sach'    => Str::slug('The Shining'),
                'id_the_loai'  => '1',
                'id_chuyen_muc'=> '1',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.CYblMPVZMKRQWC_M3sICbAHaLa?w=201&h=310&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'The Silence of the Lambs',
                'slug_sach'    => Str::slug('The Silence of the Lambs'),
                'id_the_loai'  => '1',
                'id_chuyen_muc'=> '1',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.WQC-In98A2OaCCTOV9sHdwHaMC?w=196&h=318&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],
            //2 Phiêu Lưu
            [
                'ten_sach'     => 'Robinson Crusoe',
                'slug_sach'    => Str::slug('Robinson Crusoe'),
                'id_the_loai'  => '2',
                'id_chuyen_muc'=> '2',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.evttD1Ju1Gr-65mkcZjshwAAAA?w=202&h=260&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Cuốn sách kể về Robinson Crusoe, một người đàn ông bị mắc kẹt trên một hòn đảo hoang vắng và phải tự mình tìm cách sống sót. Đây là một trong những tác phẩm kinh điển của văn học thế giới.',
                'mo_ta_chi_tiet' => 'Đây là một trong những tác phẩm kinh điển của văn học thế giới.',
            ],
            [
                'ten_sach'     => 'The Adventures of Tom Sawyer',
                'slug_sach'    => Str::slug('The Adventures of Tom Sawyer'),
                'id_the_loai'  => '2',
                'id_chuyen_muc'=> '2',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.eFTfJMgvGWcuvpY-7YhTAQHaKb?w=186&h=262&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Cuốn sách kể về cuộc phiêu lưu của Tom Sawyer, một cậu bé sống ở miền Nam Hoa Kỳ',
                'mo_ta_chi_tiet' => ' Đây là một trong những tác phẩm nổi tiếng nhất của Mark Twain.',
            ],
           
            [
                'ten_sach'     => 'The Adventures of Huckleberry Finn',
                'slug_sach'    => Str::slug('The Adventures of Huckleberry Finn'),
                'id_the_loai'  => '2',
                'id_chuyen_muc'=> '2',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.WSoeghGsApnE_L8fhBJV8QAAAA?w=186&h=275&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là một trong những tác phẩm kinh điển của văn học thế giới.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'The Hobbit',
                'slug_sach'    => Str::slug('The Hobbit'),
                'id_the_loai'  => '2',
                'id_chuyen_muc'=> '2',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.G_NxXyG1Byk2hGPmo8xhOwHaLQ?w=186&h=284&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'Treasure Island',
                'slug_sach'    => Str::slug(' Treasure Island'),
                'id_the_loai'  => '2',
                'id_chuyen_muc'=> '2',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/710K9pWWZ+L._AC_UF1000,1000_QL80_.jpg',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],

            //3 Khoa Học
            [
                'ten_sach'     => 'Những nhà khám phá',
                'slug_sach'    => Str::slug('Những nhà khám phá'),
                'id_the_loai'  => '3',
                'id_chuyen_muc'=> '3',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.XfeT9jE1Kk5jFheyX-FY4wHaEr?w=250&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Nguồn gốc các loài ',
                'slug_sach'    => Str::slug('Nguồn gốc các loài'),
                'id_the_loai'  => '3',
                'id_chuyen_muc'=> '3',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.S2Ykd90-YqrHqlyYl4TTVwHaHa?w=185&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'A Brief History of Time ',
                'slug_sach'    => Str::slug('A Brief History of Time '),
                'id_the_loai'  => '3',
                'id_chuyen_muc'=> '3',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.ty3SaF4Blg7NHQ2zNg6LXwHaLp?w=199&h=313&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'The Selfish Gene',
                'slug_sach'    => Str::slug('The Selfish Gene'),
                'id_the_loai'  => '3',
                'id_chuyen_muc'=> '3',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.z67OMmMLyegq4rJE_R7amgHaLS?w=202&h=308&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'The Structure of Scientific Revolutions',
                'slug_sach'    => Str::slug('The Structure of Scientific Revolutions'),
                'id_the_loai'  => '3',
                'id_chuyen_muc'=> '3',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.CovAtqgNSkbd8PKl--FmwwHaLc?w=201&h=310&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],
            //4 Tự Truyện
            [
                'ten_sach'     => 'Tự Truyện Của Một Yogi',
                'slug_sach'    => Str::slug('Tự Truyện Của Một Yogi'),
                'id_the_loai'  => '4',
                'id_chuyen_muc'=> '4',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.XkVLDlAZkyZA8mwoGB1fAgAAAA?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Becoming',
                'slug_sach'    => Str::slug('Becoming'),
                'id_the_loai'  => '4',
                'id_chuyen_muc'=> '4',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.DN39v-2asg_tfCe77aegJQHaHa?w=178&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'Tự Truyện Richard Branson',
                'slug_sach'    => Str::slug('Tự Truyện Richard Branson '),
                'id_the_loai'  => '4',
                'id_chuyen_muc'=> '4',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.BGWAeY32e3R6eaQNuJGBYgHaKZ?w=202&h=285&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'Tự Truyện Steve Jobs ',
                'slug_sach'    => Str::slug('Tự Truyện Steve Jobs '),
                'id_the_loai'  => '4',
                'id_chuyen_muc'=> '4',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.x9e44F8hbngGdePo6fkhpAAAAA?w=209&h=209&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'Tự Truyện Elon Musk ',
                'slug_sach'    => Str::slug('Tự Truyện Elon Musk '),
                'id_the_loai'  => '4',
                'id_chuyen_muc'=> '4',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.9tIUfKYra4KE0oY3FMwOTwHaLp?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],
            //5 Tiểu THuyết
            [
                'ten_sach'     => 'Chiến tranh và hòa bình',
                'slug_sach'    => Str::slug('Chiến tranh và hòa bình'),
                'id_the_loai'  => '5',
                'id_chuyen_muc'=> '5',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.G4FLH8f9EuGWHZikr8cx0gHaD4?w=317&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Một ngày trong thế giới đen tối',
                'slug_sach'    => Str::slug('Một ngày trong thế giới đen tối'),
                'id_the_loai'  => '5',
                'id_chuyen_muc'=> '5',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.VR1uwXPy1aEr2MvEAi-N2wHaLl?w=120&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'Tôi là lãnh đạo của mình',
                'slug_sach'    => Str::slug('Tôi là lãnh đạo của mình'),
                'id_the_loai'  => '5',
                'id_chuyen_muc'=> '5',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.-1iTsmxSaqJ1XHsLNBWM8QHaLd?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'Truyện Kiều của Nguyễn Du',
                'slug_sach'    => Str::slug('Truyện Kiều của Nguyễn Du'),
                'id_the_loai'  => '5',
                'id_chuyen_muc'=> '5',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.VvVpod3O-WpY4_CxeAy10wAAAA?w=198&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'Nhà Giả Kim',
                'slug_sach'    => Str::slug('Nhà Giả Kim'),
                'id_the_loai'  => '5',
                'id_chuyen_muc'=> '5',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.7jlnsu2BSUJ1_Vyg-wGtmwHaHa?w=193&h=193&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],
            //6 Cổ tích
            [
                'ten_sach'     => 'Cô bé lọ lem ',
                'slug_sach'    => Str::slug('Cô bé lọ lem '),
                'id_the_loai'  => '6',
                'id_chuyen_muc'=> '6',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://nhatrangbooks.com/wp-content/uploads/2020/01/lo-lem.u335.d20160613.t112423.jpg',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Hansel và Gretel ',
                'slug_sach'    => Str::slug('Hansel và Gretel '),
                'id_the_loai'  => '6',
                'id_chuyen_muc'=> '6',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.POzozgZ4CdLekMeCSPqZqQHaK0?rs=1&pid=ImgDetMain',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'Thạch Sanh',
                'slug_sach'    => Str::slug('Thạch Sanh'),
                'id_the_loai'  => '6',
                'id_chuyen_muc'=> '6',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.q3U9G4unA2PQ9vsGfHOAxwHaKJ?rs=1&pid=ImgDetMain',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'Sự tích Sơn Tinh - Thủy Tinh',
                'slug_sach'    => Str::slug('Sự tích Sơn Tinh - Thủy Tinh'),
                'id_the_loai'  => '6',
                'id_chuyen_muc'=> '6',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.elGv5AKjODQc9D5nDdjLHAHaHc?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ], 
            //7 Trinh Thám
            [
                'ten_sach'     => 'Sherlock Holmes',
                'slug_sach'    => Str::slug('Sherlock Holmes'),
                'id_the_loai'  => '7',
                'id_chuyen_muc'=> '7',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '1',
                'so_luong'     => '10',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.MvTt1eysegqhuqxsFx9yWgHaLd?w=201&h=310&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đắc Nhân Tâm (How to Win Friends and Influence People) được mệnh danh là quyển sách hay nhất, nổi tiếng nhất, bán chạy nhất và nó có tầm ảnh hưởng đi xa nhất mọi thời đại',
                'mo_ta_chi_tiet' => 'Quyển sách này cũng nêu bật lên.',
            ],
            [
                'ten_sach'     => 'Sự im lặng của bầy cừu',
                'slug_sach'    => Str::slug('Sự im lặng của bầy cừu'),
                'id_the_loai'  => '7',
                'id_chuyen_muc'=> '7',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '2',
                'so_luong'     => '20',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.nZ8A6cpwhsoB96oHI9bm9wHaL4?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Nhà giả kim (The Alchemist) của Paulo Coelho là một cuốn sách hay dành cho những người đã đánh mất đi ước mơ hoặc chưa bao giờ có nó',
                'mo_ta_chi_tiet' => 'Lời văn tuy bình dị,',
            ],
           
            [
                'ten_sach'     => 'Hỏa ngục',
                'slug_sach'    => Str::slug('Hỏa ngục'),
                'id_the_loai'  => '7',
                'id_chuyen_muc'=> '7',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '3',
                'so_luong'     => '30',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.cPT-uyOwijgGJddjSpk8IQHaLL?w=120&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Tội Ác Và Hình Phạt – Cuốn sách này nằm trong khá nhiều danh sách “những cuốn sách hàng đầu nên đọc trong suốt cuộc đời của bạn“.',
                'mo_ta_chi_tiet' => 'Câu chu',
            ],
            [
                'ten_sach'     => 'Án mạng trên sông Nile',
                'slug_sach'    => Str::slug('Án mạng trên sông Nile'),
                'id_the_loai'  => '7',
                'id_chuyen_muc'=> '7',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '4',
                'so_luong'     => '40',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.hyBfx_HkRoMM7-glrWVf6QHaKX?w=142&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Đây là cuốn sách giúp bạn trưởng thành hơn mà một lần vô tình ghé nhà sách, tôi bắt gặp tựa đề quá hay',
                'mo_ta_chi_tiet' => 'Người ta vẫg nỗi đau.',
            ],
            [
                'ten_sach'     => 'Phía sau Nghi can X ',
                'slug_sach'    => Str::slug('Phía sau Nghi can X '),
                'id_the_loai'  => '7',
                'id_chuyen_muc'=> '7',
                'nam_xuat_ban' => '2022',
                'id_tac_gia'   => '5',
                'so_luong'     => '50',
                'hinh_anh'     => 'https://th.bing.com/th/id/OIP.tx2GZ2Ava0ydbFTssk67lAAAAA?w=329&h=175&c=7&r=0&o=5&dpr=1.3&pid=1.7',
                'tinh_trang'   => random_int(0, 1),
                'mo_ta_ngan'   => 'Bạn từng trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng?',
                'mo_ta_chi_tiet' => ' Bạn có chết mòn nơi xg,Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.',
            ],
        ]);
    }
}
